MyPortfolio/Controllers/SkillController.cs
using BusinessLayer.Concrete;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MyPortfolio.Controllers;
[Authorize]
public class SkillController : Controller
{
    private readonly SkillsManager _skillsManager;

    public SkillController(SkillsManager skillsManager)
    {
        _skillsManager = skillsManager;
    }

    public IActionResult Index()
    {
        ViewBag.d1 = "Yetenek Listesi";
        ViewBag.d2 = "Yetenekler";
        ViewBag.d3 = "Yetenek Listesi";
        var skills = _skillsManager.TGetList();
        return View(skills);
    }

    [HttpGet]
    public IActionResult AddSkill()
    {
        ViewBag.d1 = "Yetenek Ekleme";
        ViewBag.d2 = "Yetenekler";
        ViewBag.d3 = "Yetenek Ekleme";
        return View();
    }

    [HttpPost]
    public IActionResult AddSkill(Skills skill)
    {
        _skillsManager.TAdd(skill);
        return RedirectToAction("Index");
    }
    public IActionResult DeleteSkill(int id)
    {
        var values = _skillsManager.TGetById(id);
        _skillsManager.TDelete(values);
        return RedirectToAction("Index");
    }
    [HttpGet]
    public IActionResult EditSkill(int id)
    {
        ViewBag.d1 = "Yetenek Güncelle";
        ViewBag.d2 = "Yetenekler";
        ViewBag.d3 = "Yetenek Güncelle";
        var values = _skillsManager.TGetById(id);
        return View(values);
    }

    [HttpPost]
    public IActionResult EditSkill(Skills skill)
    {
        _skillsManager.TUpdate(skill);
        return RedirectToAction("Index");
    }
}

MyPortfolio/Views/Skill/AddSkill.cshtml
@model dynamic

@{
    ViewBag.Title = "title";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br/> <br/>
<div class="card-header border-0">
    <h3 class="mb-0">Yetenek Ekleme Sayfası</h3>
</div>
<br/>
<form class="form-control" method="post">
    <br/>
    <br/>
    <br/>
    @Html.Label("Yetenek Başlığı")
    <input type="text "name="skill_name" class="form-control"/>
    <br/>
    <label>Değer</label>
    <input type="text "name="level" class="form-control"/>
    <br/>
    <button type="submit" class="btn btn-primary">Kaydet </button>
</form>

MyPortfolio/Views/Skill/EditSkill.cshtml
@model EntityLayer.Concrete.Skills

@{
    ViewBag.Title = "EditSkill";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br/> <br/>
<div class="card-header border-0">
    <h3 class="mb-0">Yetenek Düzenleme Sayfası</h3>
</div>
@using (Html.BeginForm("EditSkill", "Skill", FormMethod.Post))
{
    @Html.HiddenFor(x=>x.skill_id)
    <br/>
    <br/>
    <br/>
    <br/>
    @Html.Label("Yetenek Başlığı")
    @Html.TextBoxFor(x => x.skill_name, new{@class="form-control"})
    <br/>
    <label>Değer</label>
@Html.TextBoxFor(x => x.level, new{@class="form-control"})
    <br/>
    <button type="submit" class="btn btn-success">Güncelle </button>
}

MyPortfolio/Views/Skill/Index.cshtml
@using EntityLayer.Concrete
@model List<Skills>
@{
    ViewBag.Title = "title";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="card-header border-0">
    <h3 class="mb-0">Yetenek Listesi Tablosu</h3>
</div>
<!-- Light table -->
<div class="table-responsive">
    <table class="table align-items-center table-flush">
        <thead class="thead-light">
        <tr>
            <th scope="col" class="sort" data-sort="name">#</th>
            <th scope="col" class="sort" data-sort="budget">Başlık</th>
            <th scope="col" class="sort" data-sort="status">Oran</th>
            <th scope="col">Sil</th>
            <th scope="col" class="sort" data-sort="completion">Düzenle</th>
            <th scope="col"></th>
        </tr>
        </thead>
        <tbody class="list">
        @foreach (var item in Model)
        {
            <tr>
                <th>
                    @item.skill_id
                </th>
                <td class="budget">
                    @item.skill_name
                </td>

                <td>
                    <div class="d-flex align-items-center">
                        <span class="completion mr-2">@item.level %</span>
                        <div>
                            <div class="progress">
                                <div class="progress-bar bg-success" role="progressbar" aria-valuenow="@item.level" aria-valuemin="0" aria-valuemax="100" style="width: @item.level%;"></div>
                            </div>
                        </div>
                    </div>
                </td>
                <td><a href="/Skill/DeleteSkill/@item.skill_id" class="btn btn-danger">Sil</a></td>
                <td><a href="/Skill/EditSkill/@item.skill_id" class="btn btn-info">Güncelle</a></td>
            </tr>
        }
        </tbody>
    </table>
    <a href="Skill/AddSkill/" class="btn btn-primary" > Yeni Yetenek Ekle</a>
</div>