MyPortfolio/Controllers/HomePageController.cs
using BusinessLayer.Concrete;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MyPortfolio.Controllers;

[Authorize]

public class HomePageController : Controller
{
   private readonly HomePageManager _homePageManager;

   public HomePageController(HomePageManager homePageManager)
   {
       _homePageManager = homePageManager;
   }
    public IActionResult Index()
    {
        return View();
    }
    [HttpGet]
    public IActionResult EditHomePage(int id)
    {
        ViewBag.d1 = "Düzenleme";
        ViewBag.d2 = "Ana Sayfa";
        ViewBag.d3 = "Ana Sayfası";
        var values = _homePageManager.TGetById(1);
        return View(values);
    }

    [HttpPost]
    public IActionResult EditHomePage(HomePage homepage)
    {
        _homePageManager.TUpdate(homepage);
        return RedirectToAction("Index");
    }
}

MyPortfolio/Views/HomePage/Index.cshtml
@model EntityLayer.Concrete.HomePage
@{
    ViewBag.Title = "title";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<br/> <br/>
<div class="card-header border-0">
    <h3 class="mb-0">Ana Sayfa Düzenleme Sayfası</h3>
</div>
@using (Html.BeginForm("Index", "HomePage", FormMethod.Post))
{
    @Html.HiddenFor(x=>x.id)
    <br/>
    <br/>
    <br/>
    <br/>
    @Html.Label("Başlık")
    @Html.TextBoxFor(x => x.page_title, new{@class="form-control"})
    <br/>
    <label>Alt Başlık</label>
@Html.TextBoxFor(x => x.title, new{@class="form-control"})
<label>Açıklama</label>
<br/>
@Html.TextBoxFor(x => x.description, new{@class="form-control"})
    <br/>
    <button type="submit" class="btn btn-success">Güncelle </button>
}